[feature SI-6271] SOLID examples
AliceGera/examples pull request #2
Opened 2023-10-17 08:45 UTC by AliceGera

2023-10-20 07:56 UTC, roketstorm requested changes

2023-10-20 07:56 UTC, roketstorm commented on lib/SOLID/open_closed_principle.dart
> +    //позже попросят еще добавить изменения
Кто попросит?)

2023-10-20 07:56 UTC, roketstorm commented on lib/SOLID/single_responsibility_principle.dart
> +//send() {}
Нужны ли здесь комментарии?

2023-10-20 08:04 UTC, AliceGera commented on lib/SOLID/open_closed_principle.dart
> +    //позже попросят еще добавить изменения
Это я имела в виду, что когда-то в будущем, нас могут попросить что-то ещё добавить. И нам этот класс придется изменять😅(если нарушать принцип открытости и закрытости)

2023-10-20 08:06 UTC, AliceGera commented on lib/SOLID/single_responsibility_principle.dart
> +//send() {}
я их добавила, чтобы продемонстрировать. что так делать неправильно

2023-12-08 12:03 UTC, roketstorm approved these changes

2023-12-08 12:32 UTC, merged